export const ASSETS = {
  playerFull:       "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Bases/PNGs/Main Ship - Base - Full health.png",
  playerSlight:     "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Bases/PNGs/Main Ship - Base - Slight damage.png",
  playerDamaged:    "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Bases/PNGs/Main Ship - Base - Damaged.png",
  playerVeryDamaged:"assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Bases/PNGs/Main Ship - Base - Very damaged.png",
  playerEngine:     "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engines/PNGs/Main Ship - Engines - Base Engine.png",
  playerEnginePulse:"assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engines/PNGs/Main Ship - Engines - Big Pulse Engine.png",
  playerEngineBurst:"assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engines/PNGs/Main Ship - Engines - Burst Engine.png",
  playerEngineSuper:"assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engines/PNGs/Main Ship - Engines - Supercharged Engine.png",
  engineBaseIdle:   "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engine Effects/PNGs/Main Ship - Engines - Base Engine - Idle.png",
  engineBasePower:  "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engine Effects/PNGs/Main Ship - Engines - Base Engine - Powering.png",
  enginePulseIdle:  "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engine Effects/PNGs/Main Ship - Engines - Big Pulse Engine - Idle.png",
  enginePulsePower: "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engine Effects/PNGs/Main Ship - Engines - Big Pulse Engine - Powering.png",
  engineBurstIdle:  "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engine Effects/PNGs/Main Ship - Engines - Burst Engine - Idle.png",
  engineBurstPower: "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engine Effects/PNGs/Main Ship - Engines - Burst Engine - Powering.png",
  engineSuperIdle:  "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engine Effects/PNGs/Main Ship - Engines - Supercharged Engine - Idle.png",
  engineSuperPower: "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Engine Effects/PNGs/Main Ship - Engines - Supercharged Engine - Powering.png",
  shieldFront:      "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Shields/PNGs/Main Ship - Shields - Front Shield.png",
  shieldFrontSide:  "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Shields/PNGs/Main Ship - Shields - Front and Side Shield.png",
  shieldRound:      "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Shields/PNGs/Main Ship - Shields - Round Shield.png",
  shieldInvincible: "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Shields/PNGs/Main Ship - Shields - Invincibility Shield.png",
  weaponAuto:       "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Weapons/PNGs/Main Ship - Weapons - Auto Cannon.png",
  weaponRockets:    "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Weapons/PNGs/Main Ship - Weapons - Rockets.png",
  weaponZapper:     "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Weapons/PNGs/Main Ship - Weapons - Zapper.png",
  weaponBigGun:     "assets/Foozle_2DS0011_Void_MainShip/Main Ship/Main Ship - Weapons/PNGs/Main Ship - Weapons - Big Space Gun.png",
  projectileAuto:   "assets/Foozle_2DS0011_Void_MainShip/Main ship weapons/PNGs/Main ship weapon - Projectile - Auto cannon bullet.png",
  projectileRocket: "assets/Foozle_2DS0011_Void_MainShip/Main ship weapons/PNGs/Main ship weapon - Projectile - Rocket.png",
  projectileZapper: "assets/Foozle_2DS0011_Void_MainShip/Main ship weapons/PNGs/Main ship weapon - Projectile - Zapper.png",
  projectileBigGun: "assets/Foozle_2DS0011_Void_MainShip/Main ship weapons/PNGs/Main ship weapon - Projectile - Big Space Gun.png",

  enemyScout:        "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Base/PNGs/Kla'ed - Scout - Base.png",
  enemyFighter:      "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Base/PNGs/Kla'ed - Fighter - Base.png",
  enemyBomber:       "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Base/PNGs/Kla'ed - Bomber - Base.png",
  enemyFrigate:      "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Base/PNGs/Kla'ed - Frigate - Base.png",
  enemyBattlecruiser:"assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Base/PNGs/Kla'ed - Battlecruiser - Base.png",
  enemyDreadnought:  "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Base/PNGs/Kla'ed - Dreadnought - Base.png",
  klaedScoutEngine: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Engine/PNGs/Kla'ed - Scout - Engine.png",
  klaedFighterEngine: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Engine/PNGs/Kla'ed - Fighter - Engine.png",
  klaedBomberEngine: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Engine/PNGs/Kla'ed - Bomber - Engine.png",
  klaedFrigateEngine: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Engine/PNGs/Kla'ed - Frigate - Engine.png",
  klaedBattlecruiserEngine: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Engine/PNGs/Kla'ed - Battlecruiser - Engine.png",
  klaedDreadnoughtEngine: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Engine/PNGs/Kla'ed - Dreadnought - Engine.png",
  klaedScoutWeapon: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Weapons/PNGs/Kla'ed - Scout - Weapons.png",
  klaedFighterWeapon: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Weapons/PNGs/Kla'ed - Fighter - Weapons.png",
  klaedFrigateWeapon: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Weapons/PNGs/Kla'ed - Frigate - Weapons.png",
  klaedBattlecruiserWeapon: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Weapons/PNGs/Kla'ed - Battlecruiser - Weapons.png",
  klaedDreadnoughtWeapon: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Weapons/PNGs/Kla'ed - Dreadnought - Weapons.png",
  klaedScoutShield: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Shield/PNGs/Kla'ed - Scout - Shield.png",
  klaedFighterShield: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Shield/PNGs/Kla'ed - Fighter - Shield.png",
  klaedBomberShield: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Shield/PNGs/Kla'ed - Bomber - Shield.png",
  klaedFrigateShield: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Shield/PNGs/Kla'ed - Frigate - Shield.png",
  klaedBattlecruiserShield: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Shield/PNGs/Kla'ed - Battlecruiser - Shield.png",
  klaedDreadnoughtShield: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Shield/PNGs/Kla'ed - Dreadnought - Shield.png",
  klaedScoutDestruction: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Destruction/PNGs/Kla'ed - Scout - Destruction.png",
  klaedFighterDestruction: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Destruction/PNGs/Kla'ed - Fighter - Destruction.png",
  klaedBomberDestruction: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Destruction/PNGs/Kla'ed - Bomber - Destruction.png",
  klaedFrigateDestruction: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Destruction/PNGs/Kla'ed - Frigate - Destruction.png",
  klaedBattlecruiserDestruction: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Destruction/PNGs/Kla'ed - Battlecruiser - Destruction.png",
  klaedDreadnoughtDestruction: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Destruction/PNGs/Kla'ed - Dreadnought - Destruction.png",

  nairanScout:        "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Designs - Base/PNGs/Nairan - Scout - Base.png",
  nairanFighter:      "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Designs - Base/PNGs/Nairan - Fighter - Base.png",
  nairanBomber:       "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Designs - Base/PNGs/Nairan - Bomber - Base.png",
  nairanFrigate:      "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Designs - Base/PNGs/Nairan - Frigate - Base.png",
  nairanBattlecruiser:"assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Designs - Base/PNGs/Nairan - Battlecruiser - Base.png",
  nairanDreadnought:  "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Designs - Base/PNGs/Nairan - Dreadnought - Base.png",
  nairanScoutEngine: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Engine Effects/PNGs/Nairan - Scout - Engine.png",
  nairanFighterEngine: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Engine Effects/PNGs/Nairan - Fighter - Engine.png",
  nairanBomberEngine: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Engine Effects/PNGs/Nairan - Bomber - Engine.png",
  nairanFrigateEngine: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Engine Effects/PNGs/Nairan - Frigate - Engine.png",
  nairanBattlecruiserEngine: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Engine Effects/PNGs/Nairan - Battlecruiser - Engine.png",
  nairanDreadnoughtEngine: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Engine Effects/PNGs/Nairan - Dreadnought - Engine.png",
  nairanScoutWeapon: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Weapons/PNGs/Nairan - Scout - Weapons.png",
  nairanFighterWeapon: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Weapons/PNGs/Nairan - Fighter - Weapons.png",
  nairanFrigateWeapon: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Weapons/PNGs/Nairan - Frigate - Weapons.png",
  nairanBattlecruiserWeapon: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Weapons/PNGs/Nairan - Battlecruiser - Weapons.png",
  nairanDreadnoughtWeapon: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Weapons/PNGs/Nairan - Dreadnought - Weapons.png",
  nairanScoutShield: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Shields/PNGs/Nairan - Scout - Shield.png",
  nairanFighterShield: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Shields/PNGs/Nairan - Fighter - Shield.png",
  nairanBomberShield: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Shields/PNGs/Nairan - Bomber - Shield.png",
  nairanFrigateShield: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Shields/PNGs/Nairan - Frigate - Shield.png",
  nairanBattlecruiserShield: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Shields/PNGs/Nairan - Battlecruiser - Shield.png",
  nairanDreadnoughtShield: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Shields/PNGs/Nairan - Dreadnought - Shield.png",
  nairanScoutDestruction: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Destruction/PNGs/Nairan - Scout -  Destruction.png",
  nairanFighterDestruction: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Destruction/PNGs/Nairan - Fighter -  Destruction.png",
  nairanBomberDestruction: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Destruction/PNGs/Nairan - Bomber -  Destruction.png",
  nairanFrigateDestruction: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Destruction/PNGs/Nairan - Frigate -  Destruction.png",
  nairanBattlecruiserDestruction: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Destruction/PNGs/Nairan - Battlecruiser  -  Destruction.png",
  nairanDreadnoughtDestruction: "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Destruction/PNGs/Nairan - Dreadnought -  Destruction.png",

  nautolanScout:        "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Designs - Base/PNGs/Nautolan Ship - Scout - Base.png",
  nautolanFighter:      "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Designs - Base/PNGs/Nautolan Ship - Fighter - Base.png",
  nautolanBomber:       "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Designs - Base/PNGs/Nautolan Ship - Bomber - Base.png",
  nautolanFrigate:      "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Designs - Base/PNGs/Nautolan Ship - Frigate - Base.png",
  nautolanBattlecruiser:"assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Designs - Base/PNGs/Nautolan Ship - Battlecruiser - Base.png",
  nautolanDreadnought:  "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Designs - Base/PNGs/Nautolan Ship - Dreadnought - Base.png",
  nautolanScoutEngine: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Engine Effects/PNGs/Nautolan Ship - Scout - Engine Effect.png",
  nautolanFighterEngine: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Engine Effects/PNGs/Nautolan Ship - Fighter - Engine Effect.png",
  nautolanBomberEngine: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Engine Effects/PNGs/Nautolan Ship - Bomber - Engine Effect.png",
  nautolanFrigateEngine: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Engine Effects/PNGs/Nautolan Ship - Frigate - Engine Effect.png",
  nautolanBattlecruiserEngine: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Engine Effects/PNGs/Nautolan Ship - Battlecruiser - Engine Effect.png",
  nautolanDreadnoughtEngine: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Engine Effects/PNGs/Nautolan Ship - Dreadnought - Engine Effect.png",
  nautolanScoutWeapon: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapons/PNGs/Nautolan Ship - Scout - Weapons.png",
  nautolanFighterWeapon: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapons/PNGs/Nautolan Ship - Fighter - Weapons.png",
  nautolanFrigateWeapon: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapons/PNGs/Nautolan Ship - Frigate - Weapons.png",
  nautolanBattlecruiserWeapon: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapons/PNGs/Nautolan Ship - Battlecruiser - Weapons.png",
  nautolanDreadnoughtWeapon: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapons/PNGs/Nautolan Ship - Dreadnought - Weapons.png",
  nautolanScoutShield: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Shields/PNGs/Nautolan Ship - Scout - Shield.png",
  nautolanFighterShield: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Shields/PNGs/Nautolan Ship - Fighter - Shield.png",
  nautolanBomberShield: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Shields/PNGs/Nautolan Ship - Bomber - Shield.png",
  nautolanFrigateShield: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Shields/PNGs/Nautolan Ship - Frigate - Shield.png",
  nautolanBattlecruiserShield: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Shields/PNGs/Nautolan Ship - Battlecruiser - Shield.png",
  nautolanDreadnoughtShield: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Shields/PNGs/Nautolan Ship - Dreadnought - Shield.png",
  nautolanScoutDestruction: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Destruction/PNGs/Nautolan Ship - Scout.png",
  nautolanFighterDestruction: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Destruction/PNGs/Nautolan Ship - Fighter.png",
  nautolanBomberDestruction: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Destruction/PNGs/Nautolan Ship - Bomber.png",
  nautolanFrigateDestruction: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Destruction/PNGs/Nautolan Ship - Frigate.png",
  nautolanBattlecruiserDestruction: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Destruction/PNGs/Nautolan Ship - Battlecruiser.png",
  nautolanDreadnoughtDestruction: "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Destruction/PNGs/Nautolan Ship - Dreadnought.png",

  // Kla'ed projectiles
  klaedBullet:    "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Projectiles/PNGs/Kla'ed - Bullet.png",
  klaedBigBullet: "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Projectiles/PNGs/Kla'ed - Big Bullet.png",
  klaedRay:       "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Projectiles/PNGs/Kla'ed - Ray.png",
  klaedTorpedo:   "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Projectiles/PNGs/Kla'ed - Torpedo.png",
  klaedWave:      "assets/Foozle_2DS0012_Void_EnemyFleet_1/Kla'ed/Projectiles/PNGs/Kla'ed - Wave.png",
  // Nairan projectiles
  nairanBolt:     "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Weapon Effects - Projectiles/PNGs/Nairan - Bolt.png",
  nairanRay:      "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Weapon Effects - Projectiles/PNGs/Nairan - Ray.png",
  nairanRocket:   "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Weapon Effects - Projectiles/PNGs/Nairan - Rocket.png",
  nairanTorpedo:  "assets/Foozle_2DS0013_Void_EnemyFleet_2/Nairan/Weapon Effects - Projectiles/PNGs/Nairan - Torpedo.png",
  // Nautolan projectiles
  nautolanBullet:        "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapon Effects - Projectiles/PNGs/Nautolan - Bullet.png",
  nautolanRay:           "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapon Effects - Projectiles/PNGs/Nautolan - Ray.png",
  nautolanRocket:        "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapon Effects - Projectiles/PNGs/Nautolan - Rocket.png",
  nautolanBomb:          "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapon Effects - Projectiles/PNGs/Nautolan - Bomb.png",
  nautolanSpinningBullet:"assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapon Effects - Projectiles/PNGs/Nautolan - Spinning Bullet.png",
  nautolanWave:          "assets/Foozle_2DS0014_Void_EnemyFleet_3/Nautolan/Weapon Effects - Projectiles/PNGs/Nautolan - Wave.png",

  asteroid:     "assets/Foozle_2DS0015_Void_EnvironmentPack/Asteroids/PNGs/Asteroid 01 - Base.png",
  asteroidExplode:"assets/Foozle_2DS0015_Void_EnvironmentPack/Asteroids/PNGs/Asteroid 01 - Explode.png",
  asteroidFlame:"assets/Foozle_2DS0015_Void_EnvironmentPack/Effects/PNGs/Asteroid - Flame.png",
  planet:       "assets/Foozle_2DS0015_Void_EnvironmentPack/Planets/PNGs/Earth-Like planet.png",
  planetNoGlow: "assets/Foozle_2DS0015_Void_EnvironmentPack/Planets/PNGs/Earth-Like planet - Without back glow.png",

  pickupEngine:    "assets/Foozle_2DS0016_Void_PickupsPack/Engines/PNGs/Pickup Icon - Engines - Base Engine.png",
  pickupPulse:     "assets/Foozle_2DS0016_Void_PickupsPack/Engines/PNGs/Pickup Icon - Engines - Big Pulse Engine.png",
  pickupBurst:     "assets/Foozle_2DS0016_Void_PickupsPack/Engines/PNGs/Pickup Icon - Engines - Burst Engine.png",
  pickupSuper:     "assets/Foozle_2DS0016_Void_PickupsPack/Engines/PNGs/Pickup Icon - Engines - Supercharged Engine.png",
  pickupShield:    "assets/Foozle_2DS0016_Void_PickupsPack/Shield Generators/PNGs/Pickup Icon - Shield Generator - All around shield.png",
  pickupInvincible:"assets/Foozle_2DS0016_Void_PickupsPack/Shield Generators/PNGs/Pickup Icon - Shield Generator - Invincibility Shield.png",
  pickupAuto:      "assets/Foozle_2DS0016_Void_PickupsPack/Weapons/PNGs/Pickup Icon - Weapons - Auto Cannons.png",
  pickupRocket:    "assets/Foozle_2DS0016_Void_PickupsPack/Weapons/PNGs/Pickup Icon - Weapons - Rocket.png",
  pickupZapper:    "assets/Foozle_2DS0016_Void_PickupsPack/Weapons/PNGs/Pickup Icon - Weapons - Zapper.png",
  pickupBigGun:    "assets/Foozle_2DS0016_Void_PickupsPack/Weapons/PNGs/Pickup Icon - Weapons - Big Space Gun 2000.png",

  // Original UI overlays generated for Galalaxy. They remain text-free so the
  // canvas can keep all gameplay labels sharp and localizable.
  uiUpgradeCardFrame: "assets/ui/upgrade-card-frame-v2.png",
  uiUpgradeCardFrameRocket: "assets/ui/upgrade-card-frame-rocket-v1.png",
  uiBossAlertFrame:  "assets/ui/boss-alert-frame-v1.png",
  uiTitleCommandPanel: "assets/ui/title-command-panel-v1.png",
  uiStartRunButtonFrame: "assets/ui/start-run-button-frame-v1.png"
};
